# Generated by Django 4.2.1 on 2023-10-18 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "phone",
                    models.CharField(max_length=64, unique=True, verbose_name="Phone Number"),
                ),
                ("country", models.CharField(max_length=64, verbose_name="Country")),
                (
                    "telegram_age",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Telegram Age"),
                ),
                (
                    "whatsapp_age",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Whatsapp Age"),
                ),
                (
                    "telegram_avatar_url",
                    models.URLField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Telegram Avatar URL",
                    ),
                ),
                (
                    "whatsapp_avatar_url",
                    models.URLField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Whatsapp Avatar URL",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request",
                "verbose_name_plural": "Requests",
            },
        ),
    ]
