# Generated by Django 4.2.1 on 2023-10-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificationrequest",
            name="phone",
            field=models.CharField(max_length=64, verbose_name="Phone Number"),
        ),
    ]
